READ_CSV:
    START_PROCESS: "処理を開始します"
    END_PROCESS: "処理が完了しました"
    CREATE_SUBFOLDER: "サブフォルダを作成しました: {}"
    CSV_PROCESS_START: "{}を元にQRコードの生成を開始します。開始行: {}, チャンクサイズ: {}"
    CHUNK_PROCESS: "チャンク {} を処理中... 行: {} 〜 {}"
    QR_GENERATING: "QRコード生成中: 行番号 {}, ファイル名: {}"
    CSV_PROCESS_COMPLETE: "{}からQRコードの生成を完了しました。"
    CSV_READ_ERROR: "CSVファイルの読み込み中にエラーが発生しました:"
TEST_COMMON:
    SKIP_REASON: "imgフォルダに画像ファイルが存在しません"
VALIDATE:
    EMPTY_FILE: "CSVファイルが空です"
    INVALID_COLUMN_COUNT: "CSVファイルの列数が不正です"
    INVALID_EXTENSION: "{}行目: 拡張子をpngにしてください"
    INVALID_URL_FORMAT: "{}行目: URLが正しい形式ではありません"
    CONSECUTIVE_NEWLINES_FOUND: "CSVファイルに2連続以上の改行が存在します。発見された場所は次の行です: {}行目。処理を中断します。"
    FORMAT_ERROR: "CSVファイルのフォーマットが不正です"
    EMPTY_DATA_ERROR: "CSVファイルが空です"
    GENERIC_READ_ERROR: "読み込みエラーが発生しました: {}"
